### ISSUE TITLE
nginx pod Error / CrashLoopBackOff 

### ISSUE THREAD

**Issue by joknight** [vishnoisuresh/netbox-kubernetes#2]
Followed the steps to run on minikube and get error from the pod log below:

`McBookPro ➜  netbox-kubernetes git:(master) kubectl get pods -n netbox`
```
NAME                      READY     STATUS    RESTARTS   AGE
netbox-7584fdd96-pbl5l    1/1       Running   1          6m
nginx-5bb694bf8b-46gl6    0/1       Error     6          6m
postgres-f4cc88bc-rw9v4   1/1       Running   1          7m
```

`McBookPro ➜  netbox-kubernetes git:(master) kubectl logs nginx-5bb694bf8b-46gl6 -n netbox`
```
2018/02/26 20:08:22 [emerg] 1#1: host not found in upstream "netbox" in /etc/netbox-nginx/nginx.conf:21
nginx: [emerg] host not found in upstream "netbox" in /etc/netbox-nginx/nginx.conf:21
```

**Comment by vishnoisuresh** [comment]
Hi,  which version of Netbox are you using?

**Comment by joknight** [comment]
I ran the commands in this repo, so looks to be pulling `image: ninech/netbox:v2.2.6`
```
$ kubectl apply -f netbox-namespace.yaml 
$ kubectl apply -f postgres-all.yaml --namespace netbox
$ kubectl apply -f netbox-all.yaml --namespace netbox
$ kubectl apply -f nginx-all.yaml --namespace netbox
```

**Comment by vishnoisuresh** [comment]
Hi, I just cloned the repo and run these commands. I did not face the above problem. It's quite strange.       I will try to update the repo with the current version of Netbox though.

**Comment by joknight** [comment]
what version of minikube are you running? I am on `minikube version: v0.25.0` here

**Comment by vishnoisuresh** [comment]
I am using` minikube version: v0.24.1`
