### ISSUE TITLE
Deployable on Google Cloud 

### ISSUE THREAD

**Issue by changux** [vishnoisuresh/netbox-kubernetes#4]
Hi.
I'm trying to deploy those yaml files on GCP without success. The PostgreSQL is created but others not. Error reported: **Pod errors: Unschedulable**

Any suggestion?

**Comment by vishnoisuresh** [comment]
Hi, an apology for replying late. 
someone has already deployed on GKE, If you can check it out in the pull request. There is a solution for it. I hope It will work.
